---
app_port: 5555
app_listen_ip: 0.0.0.0

bye: Okay schade... bye

welcome: Hallo Raiffeisen, soll ich euch sagen, wohin wir essen gehen?

answer: Wir gehen

homepage: Restaurant picker läuft

restaurants:
  - in den Schwanen
  - ins Armenhaus
  - in die Kantine
  - zum Thai
  - über die Gasse
  - zur Taverna
